# Generated by Django 6.0.5 on 2026-05-13 03:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'Username must be unique.'}, max_length=80, unique=True)),
                ('email', models.CharField(error_messages={'unique': 'Email address must be unique.'}, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('transport_mode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be uppercase alphanumeric only.', regex='^[A-Z0-9]+$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transport Mode',
                'verbose_name_plural': 'Transport Modes',
                'db_table': 'transport_mode',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('station_type', models.CharField(choices=[('JEEPNEY_STOP', 'Jeepney Stop'), ('TRICYCLE_TERMINAL', 'Tricycle Terminal')], default='JEEPNEY_STOP', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route_code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Route code must be uppercase alphanumeric with hyphens only, no spaces or special characters.', regex='^[A-Z0-9\\-]+$')])),
                ('name', models.CharField(max_length=30)),
                ('estimated_duration_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_routes', to='transitph.station')),
                ('terminal_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_routes', to='transitph.station')),
                ('transport_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transitph.transportmode')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='FareMatrix',
            fields=[
                ('fare_matrix_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('base_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('incremental_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
                ('transport_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transitph.transportmode')),
            ],
            options={
                'verbose_name': 'Fare Matrix',
                'verbose_name_plural': 'Fare Matrices',
                'db_table': 'fare_matrix',
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('route_station_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('distance_from_prev_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transitph.route')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transitph.station')),
            ],
            options={
                'verbose_name': 'Route Station',
                'verbose_name_plural': 'Route Stations',
                'db_table': 'route_station',
                'ordering': ['route', 'sequence_order'],
                'unique_together': {('route', 'station')},
            },
        ),
    ]
