# Generated by Django 6.0.1 on 2026-05-16 07:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitph', '0002_alter_route_updated_at_alter_station_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farematrix',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='farematrix',
            name='base_km',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
