# Generated by Django 6.0.1 on 2026-05-17 12:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitph', '0003_alter_farematrix_base_fare_alter_farematrix_base_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('graph_node_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('node_type', models.CharField(choices=[('INTERSECTION', 'Intersection'), ('CORNER', 'Corner'), ('POI', 'Point of Interest'), ('VIRTUAL', 'Virtual Search Point')], default='INTERSECTION', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
            ],
            options={
                'verbose_name': 'Graph Node',
                'verbose_name_plural': 'Graph Nodes',
                'db_table': 'graph_node',
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('graph_edge_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('travel_time_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_edges', to='transitph.graphnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_edges', to='transitph.graphnode')),
            ],
            options={
                'verbose_name': 'Graph Edge',
                'verbose_name_plural': 'Graph Edges',
                'db_table': 'graph_edge',
                'unique_together': {('from_node', 'to_node')},
            },
        ),
        migrations.CreateModel(
            name='JeepneyLoop',
            fields=[
                ('jeepney_loop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Loop code must be uppercase alphanumeric with hyphens only.', regex='^[A-Z0-9\\-]+$')])),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
            ],
            options={
                'verbose_name': 'Jeepney Loop',
                'verbose_name_plural': 'Jeepney Loops',
                'db_table': 'jeepney_loop',
            },
        ),
        migrations.CreateModel(
            name='JeepneyLoopEdge',
            fields=[
                ('jeepney_loop_edge_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loop_tags', to='transitph.graphedge')),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_edges', to='transitph.jeepneyloop')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitph.admin')),
            ],
            options={
                'verbose_name': 'Jeepney Loop Edge',
                'verbose_name_plural': 'Jeepney Loop Edges',
                'db_table': 'jeepney_loop_edge',
                'ordering': ['loop', 'sequence_order'],
                'unique_together': {('loop', 'edge'), ('loop', 'sequence_order')},
            },
        ),
    ]
