# Generated by Django 6.0.1 on 2026-05-17 13:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitph', '0004_graphnode_graphedge_jeepneyloop_jeepneyloopedge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphedge',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
