# Generated by Django 6.0.1 on 2026-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitph', '0006_add_terminal_station_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphedge',
            name='road_geometry',
            field=models.JSONField(blank=True, help_text='Pre-computed OSRM road-following geometry: [{"latitude": ..., "longitude": ...}, ...]', null=True),
        ),
    ]
